### ISSUE TITLE
Documentation: Convert the project proposal in markdown format in README.md and start working on Documentation work

### ISSUE THREAD

**Issue by Abir12941** [nsusas3/SU19CSE299S01G07NSU#29]

**Comment by Abir12941** [comment]
![homepage](https://user-images.githubusercontent.com/26319280/63650785-59e5ae80-c770-11e9-9eb3-0d70dbf7ec0d.PNG)
![menu](https://user-images.githubusercontent.com/26319280/63650791-67029d80-c770-11e9-9df5-34a6d408b53f.PNG)
![division1](https://user-images.githubusercontent.com/26319280/63650795-69fd8e00-c770-11e9-828a-6e6ace41415d.PNG)
![div2](https://user-images.githubusercontent.com/26319280/63650796-6ec24200-c770-11e9-9f79-dc1393d3af14.PNG)
![footer](https://user-images.githubusercontent.com/26319280/63650797-71249c00-c770-11e9-96e4-8ae71e473484.PNG)
![log1](https://user-images.githubusercontent.com/26319280/63650799-741f8c80-c770-11e9-9f3d-5abc25c4e81c.PNG)
![map](https://user-images.githubusercontent.com/26319280/63650801-784baa00-c770-11e9-9f94-3451fc68b00d.PNG)
![booking](https://user-images.githubusercontent.com/26319280/63650802-7aae0400-c770-11e9-95f9-3913511f57ce.PNG)
![comm1](https://user-images.githubusercontent.com/26319280/63650806-7da8f480-c770-11e9-8c5d-f592232fa955.PNG)
![comm2](https://user-images.githubusercontent.com/26319280/63650807-800b4e80-c770-11e9-9b20-309eb4ea8dac.PNG)
![donate](https://user-images.githubusercontent.com/26319280/63650809-839ed580-c770-11e9-990c-eec0c66eed34.PNG)
![stripe](https://user-images.githubusercontent.com/26319280/63650812-86012f80-c770-11e9-9178-4a0550e8c203.PNG)

**Comment by Abir12941** [comment]
![reg](https://user-images.githubusercontent.com/26319280/63651996-cbc3f500-c77c-11e9-844d-8d9c6dc96f40.PNG)

**Comment by Abir1913** [comment]
Completed project report in README.MD
